OnlineAdmission/OnlineAdmission/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineAdmission.Helpers;
using OnlineAdmission.Models;
using OnlineAdmission.ModelView;
using PagedList;

namespace OnlineAdmission.Controllers
{
    public class ApplicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        Boolean flag = true;
        // GET: Applications
        public ActionResult Index()
        {
            string id = UserHelper.GetUserId(db.Users, User.Identity); 
            var application = db.Applications.Where(p=>p.ApplicationId==id).Include(a => a.Department).Include(a => a.Program).Include(a => a.User).SingleOrDefault() ;
            ViewBag.flag =IsCompleted();
            return View(application);
        }

        public bool IsCompleted()
        {
            string id = UserHelper.GetUserId(db.Users, User.Identity);
            var application = db.Applications.Where(p => p.ApplicationId == id).Include(a => a.Department).Include(a => a.Program).Include(a => a.User).SingleOrDefault();
            if (application != null)
            {
                if (application.Status == Status.Complete)
                    return false;
            }
            return true;
        }
        public ActionResult IndexAdmin(string sortDir, string searchString, string currentFilter, string searchStatus, string currentStatus, int? page, string sortOrder = "")
        {

            //ViewBag.SearchString = searchString;
            //var applications = db.Applications.Include(a => a.Department).Include(a => a.Program).Include(a => a.User).OrderBy(h => h.FirstName).AsQueryable();

            //if (!string.IsNullOrEmpty(searchString))
            //    applications = applications.Where(s => s.FirstName.Contains(searchString));
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;
            sortOrder = sortOrder + "_" + sortDir;
            bool flag = false;
            if (searchStatus !="")
            {
                //page = 1;
                ViewBag.currentStatus = searchStatus;
                flag = true;
            }

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            var applications = db.Applications.Include(h => h.Department).Include(h => h.Program).Include(a => a.User);

            if (!String.IsNullOrEmpty(searchString)&& !flag)
                applications = applications.Where(p => p.FirstName.Contains(searchString));
            else
            if (!String.IsNullOrEmpty(searchStatus) && flag)
                applications = applications.Where(p => p.StatusString.Contains(searchStatus));

            switch (sortOrder.ToLower())
            {
                case "firstname_desc":
                    applications = applications.OrderByDescending(p => p.FirstName);
                    break;
                case "department_asc":
                    applications = applications.OrderBy(h => h.Department.Name);
                    break;
                case "department_desc":
                    applications = applications.OrderByDescending(p => p.Department.Name);
                    break;
                case "program_asc":
                    applications = applications.OrderBy(p => p.Program.Name);
                    break;
                case "program_desc":
                    applications = applications.OrderByDescending(p => p.Program.Name);
                    break;
                case "registrationdate_asc":
                    applications = applications.OrderBy(p => p.RegistrationDate);
                    break;
                case "registrationdate_desc":
                    applications = applications.OrderByDescending(p => p.RegistrationDate);
                    break;
                case "status_desc":
                    applications = applications.OrderByDescending(p => p.StatusString);
                    break;
                default:  // Description ascending 
                    applications = applications.OrderBy(p => p.FirstName);
                    break;
            }

            int pageSize =2;
            int pageNumber = (page ?? 1);
            var data = applications.ToPagedList(pageNumber, pageSize);

            return View("IndexAdmin", data);

        }


        // GET: Applications/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Application application = db.Applications.Where(p => p.ApplicationId == id).Include(a => a.Department).Include(a => a.Program).Include(a => a.User).FirstOrDefault();
            //Application application = db.Applications.Find(id);

            ViewBag.ApplicationId = id;
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }


        public ActionResult DetailsAdmin(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Where(p => p.ApplicationId == id).Include(a => a.Department).Include(a => a.Program).Include(a => a.User).FirstOrDefault();
            //Application application = db.Applications.Find(id);

            ViewBag.ApplicationId = id;
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }




        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            ViewBag.ProgarmId = new SelectList(db.Programs, "ProgarmId", "Name");
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Id");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ApplicationId,FirstName,LastName,TelePhoneNumber,DepartmentId,ProgarmId,RegistrationDate,StatusString")] Application application)
        public ActionResult Create(ApplicationViewModel applicationVM)
        {
            Application application = new Application();

            if (ModelState.IsValid)
            {
                application.ApplicationId = UserHelper.GetUserId(db.Users, User.Identity);
                application.FirstName = applicationVM.FirstName;
                application.LastName = applicationVM.LastName;
                application.ProgarmId = applicationVM.ProgarmId;
                application.DepartmentId = applicationVM.DepartmentId;
                application.TelePhoneNumber = applicationVM.TelePhoneNumber;
                application.Status = Status.Draft;
                application.RegistrationDate = DateTime.Now;
                if (applicationVM.Photo != null)
                    application.Photo = ImageConverter.ByteArrayFromPostedFile(applicationVM.Photo);

                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", applicationVM.DepartmentId);
            ViewBag.ProgarmId = new SelectList(db.Programs, "ProgarmId", "Name", applicationVM.ProgarmId);
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Id", applicationVM.ApplicationId);
            return View(applicationVM);
        
    }

        // GET: Applications/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ApplicationViewModel applicationViewModel = new ApplicationViewModel();

            applicationViewModel.ApplicationId = UserHelper.GetUserId(db.Users, User.Identity);
            applicationViewModel.FirstName = application.FirstName;
            applicationViewModel.LastName = application.LastName;
            applicationViewModel.ProgarmId = application.ProgarmId;
            applicationViewModel.DepartmentId = application.DepartmentId;
            applicationViewModel.TelePhoneNumber = application.TelePhoneNumber;
            //applicationViewModel.Status = Status.Saved;
            application.RegistrationDate = DateTime.Now;
            if (application.Photo != null)
                applicationViewModel.PhotoDB = application.Photo;



            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", applicationViewModel.DepartmentId);
            ViewBag.ProgarmId = new SelectList(db.Programs, "ProgarmId", "Name", applicationViewModel.ProgarmId);
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Id", applicationViewModel.ApplicationId);
            return View(applicationViewModel);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApplicationViewModel applicationVM)
        {

OnlineAdmission/OnlineAdmission/Controllers/EducationDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineAdmission.Models;
using OnlineAdmission.Helpers;

namespace OnlineAdmission.Controllers
{
    public class EducationDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: EducationDetails
        public ActionResult Index()
        {
            string id = UserHelper.GetUserId(db.Users, User.Identity);
            var educationDetails = db.EducationDetails.Where(p=>p.ApplicationId==id).Include(e => e.Application);
            ViewBag.flag = IsCompleted();
            return View(educationDetails.ToList());
        }
        public bool IsCompleted()
        {
            string id = UserHelper.GetUserId(db.Users, User.Identity);
            var application = db.Applications.Where(p => p.ApplicationId == id).Include(a => a.Department).Include(a => a.Program).Include(a => a.User).SingleOrDefault();
            if (application != null)
            {
                if (application.Status == Status.Complete)
                    return false;
            }
            return true;
        }

        // GET: EducationDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            return View(educationDetail);
        }
        // GET: EducationDetails/EducationAdmin/5
        public ActionResult EducationAdmin(string id)
        {
            var educationDetails = db.EducationDetails.Where(p => p.ApplicationId == id).Include(e => e.Application);
            ViewBag.applicationId = id;
            return View(educationDetails.ToList());
        }


        // GET: EducationDetails/Create
        public ActionResult Create()
        {
            //ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "Id");
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Id");
            return View();
        }

        // POST: EducationDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ApplicationId,Qualification,Year,Duration,BoardUniversity,Subjects,Percentage")] EducationDetail educationDetail)
        {
            if (ModelState.IsValid)
            {
                educationDetail.ApplicationId = UserHelper.GetUserId(db.Users, User.Identity);

                db.EducationDetails.Add(educationDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            //ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Id");
            return View(educationDetail);
        }

        // GET: EducationDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            //ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            ViewBag.ApplicationId = UserHelper.GetUserId(db.Users, User.Identity);
            return View(educationDetail);
        }

        // POST: EducationDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationId,Qualification,Year,Duration,BoardUniversity,Subjects,Percentage")] EducationDetail educationDetail)
        {
            if (ModelState.IsValid)
            {
                educationDetail.ApplicationId=UserHelper.GetUserId(db.Users, User.Identity); ;
                db.Entry(educationDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            return View(educationDetail);
        }

        // GET: EducationDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            return View(educationDetail);
        }

        // POST: EducationDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            db.EducationDetails.Remove(educationDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineAdmission/OnlineAdmission/Views/Shared/_Layout.cshtml
@using OnlineAdmission.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("  ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse"  >
                <ul class="nav navbar-nav">
                    @if ((User.Identity.IsAuthenticated) && (!User.IsInRole(RoleName.CanManage)))
                    {
                        < li > @Html.ActionLink("Application", "Index", "Applications", new { area = "" }, new { @class = "navbar-brand" }) </ li >

                        @*< li > @Html.ActionLink("Education Details", "Index", "EducationDetails", new { area = "" }, new { @class = "navbar-brand" }) </ li >

                        < li > @Html.ActionLink("Enclosed Documents", "Index", "EnclosedDocuments", new { area = "" }, new { @class = "navbar-brand" }) </ li >*@
                    }
                    @if (User.IsInRole(RoleName.CanManage))
                    {
                        < li > @Html.ActionLink("Student Application", "IndexAdmin", "Applications", new { area = "" }, new { @class = "navbar-brand" }) </ li >
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p  class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineAdmission/OnlineAdmission/Views/Shared/_SearchResults.cshtml
@model IEnumerable<OnlineAdmission.Models.Application>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.ApplicationId)*@
            Appliation Id
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.FirstName)*@ Student Name
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.Department)*@
            Degree
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Program)*@
            Program

        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.User.Email)
            </th>*@

        @*<th>
                @Html.DisplayNameFor(model => model.TelePhoneNumber)
            </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.RegistrationDate)*@
            Registration Date
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.StatusString)*@
            Status
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Program.Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>*@

            @*<td>
                    @Html.DisplayFor(modelItem => item.TelePhoneNumber)
                </td>*@
            <td>
                @*@Html.DisplayFor(modelItem => item.RegistrationDate)*@
                @item.RegistrationDate.Value.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusString)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Photo)
                </td>*@
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ApplicationId }) |*@
                @Html.ActionLink("Details", "Details", new { id = item.ApplicationId })
                @*@Html.ActionLink("Delete", "Delete", new { id = item.ApplicationId })*@
            </td>
        </tr>
    }